import Link from "next/link";
import { ArrowRight, CheckCircle2, Sparkles } from "lucide-react";
import { Navbar } from "@/components/layout/navbar";
import { Button } from "@/components/ui/button";

const features = [
  "AI-generated speaker-ready narratives",
  "Brand-styled decks in seconds",
  "Persona-aware tone and structure"
];

const useCases = [
  "Startup investor pitch decks",
  "Internal strategy and board updates",
  "University and student project presentations"
];
const trustBadges = ["SOC 2 Ready Workflow", "FastAPI + Next.js Stack", "Prompt-Based Revision"];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-hero-gradient">
      <Navbar />

      <section className="mx-auto max-w-6xl px-4 pb-14 pt-16 sm:px-6 sm:pb-16 sm:pt-20">
        <div className="grid items-center gap-10 lg:grid-cols-[1.05fr_0.95fr]">
          <div>
            <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-400/40 bg-violet-500/10 px-3 py-1 text-xs text-violet-200">
              <Sparkles className="h-3.5 w-3.5" /> Premium AI Presentation Studio
            </div>
            <h1 className="text-4xl font-semibold leading-tight text-white md:text-6xl">Build stunning decks with SlideGen AI</h1>
            <p className="mt-5 max-w-2xl text-base text-slate-300 md:text-lg">
              Turn rough notes into polished, on-brand slides with narrative flow, visual harmony, and presentation-ready structure.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="/dashboard"><Button>Open Dashboard <ArrowRight className="h-4 w-4" /></Button></Link>
              <Link href="#features">
                <Button variant="secondary" type="button">
                  See features
                </Button>
              </Link>
            </div>
            <div className="mt-5 flex flex-wrap gap-2">
              {trustBadges.map((badge) => (
                <span key={badge} className="rounded-full border border-white/15 bg-white/[0.03] px-3 py-1 text-xs text-slate-300">
                  {badge}
                </span>
              ))}
            </div>
          </div>

          <div className="panel bg-gradient-to-br from-white/[0.07] via-white/[0.03] to-cyan-500/10 p-6 sm:p-7">
            <p className="text-xs uppercase tracking-[0.18em] text-slate-400">How it works</p>
            <h3 className="mt-2 text-xl font-semibold text-white">Real pipeline</h3>
            <ol className="mt-5 space-y-3 text-sm text-slate-300">
              <li className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                <span className="font-semibold text-cyan-200">1. Upload</span>
                <p className="mt-1 text-xs text-slate-400">PDF, DOCX, or TXT — text is extracted on the server with pypdf / python-docx.</p>
              </li>
              <li className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                <span className="font-semibold text-cyan-200">2. Analyze &amp; outline</span>
                <p className="mt-1 text-xs text-slate-400">
                  With OpenAI configured, models shape the deck; otherwise outlines are built from your document structure.
                </p>
              </li>
              <li className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
                <span className="font-semibold text-cyan-200">3. Export</span>
                <p className="mt-1 text-xs text-slate-400">Download a real .pptx generated by python-pptx from your current outline and notes.</p>
              </li>
            </ol>
          </div>
        </div>
      </section>

      <section id="features" className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-12">
        <h2 className="text-2xl font-semibold text-white">Features</h2>
        <p className="mt-2 max-w-2xl text-sm text-slate-400">Production-minded SaaS workflow from document intake to presentation export.</p>
        <div className="mt-6 grid gap-4 md:grid-cols-3">
          {features.map((item) => (
            <article key={item} className="panel p-5 transition hover:border-white/20 hover:bg-white/[0.07]">
              <CheckCircle2 className="mb-3 h-5 w-5 text-cyan-300" />
              <p className="text-sm leading-relaxed text-slate-200">{item}</p>
            </article>
          ))}
        </div>
      </section>

      <section id="use-cases" className="mx-auto max-w-6xl px-4 py-10 sm:px-6 sm:py-12">
        <h2 className="text-2xl font-semibold text-white">Use Cases</h2>
        <div className="mt-6 grid gap-4 md:grid-cols-3">
          {useCases.map((item) => (
            <article key={item} className="panel p-5 transition hover:border-white/20 hover:bg-white/[0.07]">
              <p className="text-sm leading-relaxed text-slate-200">{item}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="panel flex flex-col items-start justify-between gap-6 bg-gradient-to-r from-violet-500/15 via-white/[0.02] to-cyan-500/15 p-6 sm:p-8 md:flex-row md:items-center">
          <div>
            <h3 className="text-2xl font-semibold text-white">Ready to generate your next deck?</h3>
            <p className="mt-2 text-sm text-slate-300">Launch your presentation workflow with a premium AI-first experience.</p>
          </div>
          <Link href="/dashboard/new"><Button>Get Started</Button></Link>
        </div>
      </section>
    </main>
  );
}
